name: Playwright Tests with Allure Report

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  e2eTest:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v4
      
      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Install Playwright
      - name: Install Playwright
        run: npx playwright install --with-deps
      
      # Run tests with Allure reporting
      - name: Run Playwright tests with Allure
        run: |
          set -e
          start_time=$(date +%s)
          allurectl watch -- npx playwright test || true
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "DURATION_SECONDS=$duration" >> $GITHUB_ENV
        env:
          ALLURE_RESULTS: './allure-results'
      
      # Upload Playwright test results
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: test-results
          retention-days: 20
      
      # Upload Allure results
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 20
      
      # Checkout gh-pages branch for history
      - uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages
      
      # Generate Allure report
      - uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
      
      # Deploy report to GitHub Pages
      - name: Deploy Allure report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
      
      # Setup Java for notifications
      - name: Setup Java 17
        if: always()
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # Prepare duration file for Allure Notifications
      - name: Prepare duration file
        if: always()
        run: |
          echo "{\"time\": {\"duration\": ${{ env.DURATION_SECONDS }}}" > duration.json
          mkdir -p notifications
          cp duration.json notifications/
      
      # Send Telegram notification
      - name: Send Telegram notification
        if: always()
        run: |
          export TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
          export TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
          java -DconfigFile=notifications/telegram.json -jar notifications/allure-notifications-4.9.0.jar
